version: '2'
services:
  postgres:
    image: postgres
  web:
    build: .
    command: mix phoenix.server
    volumes:
      - ../:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres